package logic;

import com.itextpdf.kernel.font.PdfFont;
import com.itextpdf.kernel.font.PdfFontFactory;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Paragraph;

import java.io.IOException;

public class MyPDFWriter implements Writer {
    private final Document doc;
    private final String filePath;
    private final PdfWriter writer;
    private final PdfDocument pdfDoc;
    private PdfFont fontMedium;
    private PdfFont fontLight;
    private PdfFont fontSemiBold;

    public MyPDFWriter(String filePath) throws IOException {
        this.filePath = filePath + "/AutoGenerated.pdf";
        this.writer = new PdfWriter(filePath);
        this.pdfDoc = new PdfDocument(writer);
        this.doc = new Document(pdfDoc);
        initFonts();
    }

    public MyPDFWriter() throws IOException {
        this.filePath = "src/test/AutoGenerated.pdf";
        this.writer = new PdfWriter(filePath);
        this.pdfDoc = new PdfDocument(writer);
        this.doc = new Document(pdfDoc);
        initFonts();
    }
    private void initFonts() throws IOException {
        fontMedium = PdfFontFactory.createFont("src/main/resources/fonts/SF UI Display/sf-ui-display-medium-58646be638f96.otf", "Identity-H", true);
        fontSemiBold = PdfFontFactory.createFont("src/main/resources/fonts/SF UI Display/sf-ui-display-semibold-58646eddcae92.otf",  "Identity-H",true);
        fontLight = PdfFontFactory.createFont("src/main/resources/fonts/SF UI Display/sf-ui-display-light-58646b33e0551.otf", "Identity-H", true);
    }

    public boolean write(IncomingInfo info){
        //берём полученую проверенную информацию и записываем в файл. По окончании возвращаем true в случае успеха и false при неудаче
         //TODO добавить ко всем объектам Paragraph шрифт, размер, позицию на странице
        //слияние имени и фамилии в одну строку
        String fullName = info.getName() + " " + info.getSurname();
        Paragraph name = new Paragraph(fullName);
        name.setFont(fontMedium);
        name.setFontSize(30);
        Paragraph position = new Paragraph(info.getPosition());
        position.setFont(fontLight);
        position.setFontSize(20);
        //TODO сделать проверку номера на пул номеров компании
        Paragraph phone = new Paragraph(info.getPhone());
        phone.setFont(fontLight);
        phone.setFontSize(20);
        //TODO сделать проверку почты на соответствие домену компании
        Paragraph email = new Paragraph(info.getEmail());
        email.setFont(fontLight);
        email.setFontSize(20);
        try {
            doc.add(name);
            doc.add(position);
            doc.add(phone);
            doc.add(email);
            //TODO возможно, стоит сделать проверку на пустой объект не в этом месте
            if(info.getSkype() != null) {
                Paragraph skype = new Paragraph(info.getSkype());
                skype.setFont(fontLight);
                skype.setFontSize(20);
                doc.add(skype);
            }
            //TODO возможно, стоит сделать проверку на пустой объект не в этом месте
            if(info.getIcq() != null) {
                Paragraph icq =  new Paragraph(info.getIcq());
                icq.setFont(fontLight);
                icq.setFontSize(20);
                doc.add(icq);
            }
            doc.close();
            System.out.println("Successfully written in file " + filePath);
            return true;
        } catch (Exception e) {
            e.printStackTrace();
            doc.close();
            return false;
        }
        finally {
            doc.close();
        }
//        try {
//            PdfWriter.getInstance(doc, new FileOutputStream(filePath));
//            doc.open();
//            doc.addTitle(info.getName() + " "+ info.getSurname());
//            doc.addSubject(info.getPosition());
//            doc.close();
//            System.out.println("Успешно записано в файл " + filePath);
//            return true;
//        } catch (DocumentException de) {
//            System.err.println(de.getMessage());
//        } finally {
//            doc.close();
//        }
//        return false;
    }
    public String getFilePath(){
        return filePath;
    }
}
