package logic;

import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.text.DocumentException;

import java.io.FileNotFoundException;
import java.util.Arrays;

public class MyPDFWriter implements Writer {
    private final Document doc;
    private final String filePath;
    private final PdfWriter writer;
    private final PdfDocument pdfDoc;

    public MyPDFWriter(String filePath) throws FileNotFoundException {
        this.filePath = filePath + "/AutoGenerated.pdf";
        this.writer = new PdfWriter(filePath);
        this.pdfDoc = new PdfDocument(writer);
        this.doc = new Document(pdfDoc);
    }

    public MyPDFWriter() throws FileNotFoundException {
        this.filePath = "src/test/AutoGenerated.pdf";
        this.writer = new PdfWriter(filePath);
        this.pdfDoc = new PdfDocument(writer);
        this.  doc = new Document(pdfDoc);
    }

    public boolean write(IncomingInfo info) throws FileNotFoundException, DocumentException {
        //берём полученую информацию и записываем в файл. По окончании возвращаем true в случае успеха и false при неудаче
         //TODO добавить ко всем объектам Paragraph шрифт, размер, позицию на странице
        Paragraph name = new Paragraph(info.getName());
        Paragraph surname = new Paragraph(info.getSurname());
        Paragraph position = new Paragraph(info.getPosition());
        //TODO сделать проверку номера на пул номеров компании
        Paragraph phone = new Paragraph(Arrays.toString(info.getPhone()));
        //TODO сделать проверку почты на соответствие домену компании
        Paragraph email = new Paragraph(info.getEmail());
        Paragraph skype = new Paragraph(info.getSkype());
        Paragraph icq =  new Paragraph(Arrays.toString(info.getIcq()));
        try {
            doc.add(name);
            doc.add(surname);
            doc.add(position);
            doc.add(phone);
            doc.add(email);
            //TODO сделать проверку на пусто объект не в этом месте
            if(info.getSkype() != null) {
                doc.add(skype);
            }
            //TODO сделать проверку на пустой объект не в этом месте
            if(info.getIcq() != null) {
                doc.add(icq);
            }
            doc.close();
            System.out.println("Успешно записано в файл " + filePath);
            return true;
        } catch (Exception e) {
            e.printStackTrace();
            doc.close();
            return false;
        }finally {
            doc.close();
        }
//        try {
//            PdfWriter.getInstance(doc, new FileOutputStream(filePath));
//            doc.open();
//            doc.addTitle(info.getName() + " "+ info.getSurname());
//            doc.addSubject(info.getPosition());
//            doc.close();
//            System.out.println("Успешно записано в файл " + filePath);
//            return true;
//        } catch (DocumentException de) {
//            System.err.println(de.getMessage());
//        } finally {
//            doc.close();
//        }
//        return false;
    }
    public String getFilePath(){
        return filePath;
    }
}
